# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Tests for OMN-10352: plan_to_tickets auto-creates epic and injects epic_id frontmatter.

Validates that:
1. A plan with no frontmatter triggers epic creation and has epic_id injected.
2. A re-run on a plan that already has a valid epic_id does NOT call create_issue for the
   epic again — the existing identifier is reused (idempotency).

These tests exercise the helper functions defined in the SKILL.md Main Execution Flow
section, extracted here as importable pure-Python utilities so they can be unit-tested
without the full omniclaude plugin stack.
"""

import re
import tempfile
from pathlib import Path
from unittest.mock import MagicMock

import pytest
import yaml

# ---------------------------------------------------------------------------
# Helpers extracted from SKILL.md Main Execution Flow (inline implementation
# so we can unit-test without the plugin runtime).
# ---------------------------------------------------------------------------

_EPIC_ID_RE = re.compile(r"^OMN-\d+$")


def _read_frontmatter(content: str) -> tuple[dict, str]:
    """Parse YAML frontmatter. Returns (fm_dict, body)."""
    fm_match = re.match(r"^---\s*\n(.*?)\n---\s*\n", content, re.DOTALL)
    if fm_match:
        try:
            fm = yaml.safe_load(fm_match.group(1)) or {}
            if isinstance(fm, dict):
                body = content[fm_match.end() :]
                return fm, body
        except yaml.YAMLError:
            pass
    return {}, content


def _write_frontmatter(plan_path: str, fm: dict, body: str) -> None:
    """Serialise frontmatter + body back to the plan file."""
    fm_block = yaml.dump(fm, default_flow_style=False, allow_unicode=True).strip()
    new_content = f"---\n{fm_block}\n---\n{body}"
    Path(plan_path).write_text(new_content, encoding="utf-8")


def _extract_frontmatter_epic_id(plan_path: str, content: str) -> str | None:
    """Return epic_id from YAML frontmatter or companion .contract.yaml, or None."""
    fm, _ = _read_frontmatter(content)
    if fm.get("epic_id"):
        return str(fm["epic_id"]).strip()

    companion = Path(plan_path).with_suffix(".contract.yaml")
    if companion.exists():
        try:
            data = yaml.safe_load(companion.read_text(encoding="utf-8"))
            if isinstance(data, dict) and data.get("epic_id"):
                return str(data["epic_id"]).strip()
        except (yaml.YAMLError, OSError):
            pass

    return None


def _run_step4(
    plan_path: str, content: str, tracker: MagicMock, team: str = "Omninode"
) -> dict | None:
    """Simulate the Step 4 logic from SKILL.md Main Execution Flow.

    Returns the resolved epic dict.
    """
    existing_epic_id = _extract_frontmatter_epic_id(plan_path, content)
    if existing_epic_id and _EPIC_ID_RE.match(existing_epic_id):
        # Reuse path — look up by identifier
        found = tracker.list_issues(query=existing_epic_id, team=team, limit=10)
        matches = [
            i
            for i in found.get("issues", [])
            if i.get("identifier") == existing_epic_id
        ]
        if matches:
            return matches[0]
        # Fall through to create if not found in Linear
    # Create new epic
    epic = tracker.create_issue(
        title="My Plan Epic",
        team=team,
        description="Epic created from plan file.\n\n**Auto-generated by /plan-to-tickets**",
    )
    # Inject epic_id into frontmatter
    new_identifier = epic.get("identifier", "")
    if new_identifier and _EPIC_ID_RE.match(new_identifier):
        fm, body = _read_frontmatter(content)
        fm["epic_id"] = new_identifier
        _write_frontmatter(plan_path, fm, body)
    return epic


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

MINIMAL_PLAN = """\
# My Plan Epic

## Task 1: First task

Implement the first thing.

## Task 2: Second task

Implement the second thing.
"""

PLAN_WITH_EXISTING_FRONTMATTER = """\
---
epic_id: OMN-9999
plan_version: 1.0.0
---
# My Plan Epic

## Task 1: First task

Implement the first thing.
"""


@pytest.mark.unit
def test_plan_with_no_frontmatter_creates_epic_and_injects_epic_id() -> None:
    """Plan with no frontmatter → epic created, epic_id injected into file."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(MINIMAL_PLAN)
        plan_path = f.name

    try:
        tracker = MagicMock()
        tracker.create_issue.return_value = {
            "id": "abc123",
            "identifier": "OMN-1234",
            "title": "My Plan Epic",
            "url": "https://linear.app/omninode/issue/OMN-1234",
        }

        content = Path(plan_path).read_text()
        assert _extract_frontmatter_epic_id(plan_path, content) is None, (
            "Should have no epic_id before run"
        )

        epic = _run_step4(plan_path, content, tracker)

        # Epic was created via tracker
        tracker.create_issue.assert_called_once()
        create_call_kwargs = tracker.create_issue.call_args
        assert create_call_kwargs is not None
        assert epic is not None
        assert epic["identifier"] == "OMN-1234"

        # epic_id injected into plan frontmatter on disk
        updated_content = Path(plan_path).read_text()
        fm, body = _read_frontmatter(updated_content)
        assert fm.get("epic_id") == "OMN-1234", (
            f"epic_id not injected; frontmatter={fm}"
        )

        # Body is preserved
        assert "## Task 1: First task" in body
        assert "## Task 2: Second task" in body

    finally:
        Path(plan_path).unlink(missing_ok=True)


@pytest.mark.unit
def test_plan_with_existing_epic_id_reuses_without_creating() -> None:
    """Re-run on plan that already has a valid epic_id does NOT call create_issue for the epic."""
    with tempfile.NamedTemporaryFile(mode="w", suffix=".md", delete=False) as f:
        f.write(PLAN_WITH_EXISTING_FRONTMATTER)
        plan_path = f.name

    try:
        tracker = MagicMock()
        tracker.list_issues.return_value = {
            "issues": [
                {
                    "id": "xyz999",
                    "identifier": "OMN-9999",
                    "title": "My Plan Epic",
                }
            ]
        }

        content = Path(plan_path).read_text()
        assert _extract_frontmatter_epic_id(plan_path, content) == "OMN-9999"

        epic = _run_step4(plan_path, content, tracker)

        # create_issue must NOT have been called (we reused the existing epic)
        tracker.create_issue.assert_not_called()

        # list_issues WAS called (to look up the existing epic by identifier)
        tracker.list_issues.assert_called_once()

        assert epic is not None
        assert epic["identifier"] == "OMN-9999"

        # Plan file on disk is unchanged (no re-injection needed)
        updated_content = Path(plan_path).read_text()
        assert updated_content == PLAN_WITH_EXISTING_FRONTMATTER

    finally:
        Path(plan_path).unlink(missing_ok=True)
