#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
# GENERATED BY omnibase_core/scripts/gen_hook_bits.py — DO NOT EDIT
# Regenerate via: uv run python scripts/gen_hook_bits.py --write <this-file>

HOOK_BITS_DEFAULT_MASK=0x7ffffffffffffff

# hook_bits_bit_for_name NAME
#   Prints the bit assigned to NAME. Bash 3.2 has no associative arrays, and
#   Claude hook launchers use the system bash on macOS, so keep this table as a
#   portable case statement instead of `declare -A`.
hook_bits_bit_for_name() {
    case "${1:-}" in
        CI_REMINDER) echo 0x1 ;;
        RUFF_FIX) echo 0x2 ;;
        CONVENTION_INJECTOR) echo 0x4 ;;
        EPIC_POSTACTION_GATE) echo 0x8 ;;
        EPIC_PREFLIGHT_GATE) echo 0x10 ;;
        FILE_PATH_CONVENTION_INJECT) echo 0x20 ;;
        HOOK_DISPATCH_CLAIM_POSTTOOL) echo 0x40 ;;
        HOOK_DISPATCH_CLAIM_PRETOOL) echo 0x80 ;;
        HOOK_IDLE_NOTIFICATION_RATELIMIT) echo 0x100 ;;
        HOOK_VERIFIER_ROLE_GUARD) echo 0x200 ;;
        PERMISSION_DENIED_LOGGER) echo 0x400 ;;
        POST_SKILL_DELEGATION_ENFORCER) echo 0x800 ;;
        POST_TOOL_DELEGATION_COUNTER) echo 0x1000 ;;
        POST_TOOL_USE_QUALITY) echo 0x2000 ;;
        TEST_REMINDER) echo 0x4000 ;;
        POST_TOOL_AGENT_RESULT_VERIFIER) echo 0x8000 ;;
        AUTO_CHECKPOINT) echo 0x10000 ;;
        AUTO_HOSTILE_REVIEW) echo 0x20000 ;;
        CHANGESET_GUARD_POST) echo 0x40000 ;;
        POST_TOOL_COMMIT_VERIFY) echo 0x80000 ;;
        POST_TOOL_CRON_ACTION_GUARD) echo 0x100000 ;;
        ENV_SYNC) echo 0x200000 ;;
        POST_TOOL_KAFKA_POISON_MESSAGE_GUARD) echo 0x400000 ;;
        POST_TOOL_OUTPUT_SUPPRESSOR) echo 0x800000 ;;
        POST_TOOL_RETURN_PATH_AUDITOR) echo 0x1000000 ;;
        POST_TOOL_STATE_VERIFY) echo 0x2000000 ;;
        POST_TOOL_SUBAGENT_TOOL_LOG) echo 0x4000000 ;;
        TEAM_OBSERVABILITY) echo 0x8000000 ;;
        POST_TOOL_TSC_CHECK) echo 0x10000000 ;;
        PRE_COMPACT) echo 0x20000000 ;;
        PRE_TOOL_USE_QUALITY) echo 0x40000000 ;;
        PRE_TOOL_AGENT_DISPATCH_GATE) echo 0x80000000 ;;
        PRE_TOOL_AGENT_TOOL_GATE) echo 0x100000000 ;;
        PRE_TOOL_AUTHORIZATION_SHIM) echo 0x200000000 ;;
        BASH_GUARD) echo 0x400000000 ;;
        BRANCH_PROTECTION_GUARD) echo 0x800000000 ;;
        CHANGESET_GUARD_PRE) echo 0x1000000000 ;;
        CONTEXT_SCOPE_AUDITOR) echo 0x2000000000 ;;
        DISPATCH_GUARD) echo 0x4000000000 ;;
        DISPATCH_GUARD_TICKET_EVIDENCE) echo 0x8000000000 ;;
        DISPATCH_MODE_GUARDRAIL) echo 0x10000000000 ;;
        DOD_COMPLETION_GUARD) echo 0x20000000000 ;;
        HOSTILE_REVIEW_GATE) echo 0x40000000000 ;;
        LINEAR_DONE_VERIFY) echo 0x80000000000 ;;
        MODEL_ROUTER) echo 0x100000000000 ;;
        OVERSEER_FOREGROUND_BLOCK) echo 0x200000000000 ;;
        PIPELINE_GATE) echo 0x400000000000 ;;
        PLAN_EXISTENCE_GATE) echo 0x800000000000 ;;
        POLY_ENFORCER) echo 0x1000000000000 ;;
        PREPUSH_VALIDATOR) echo 0x2000000000000 ;;
        SCOPE_GATE) echo 0x4000000000000 ;;
        SWEEP_PREFLIGHT) echo 0x8000000000000 ;;
        TDD_DISPATCH_GATE) echo 0x10000000000000 ;;
        TEAM_LEAD_GUARD) echo 0x20000000000000 ;;
        WORKFLOW_GUARD) echo 0x40000000000000 ;;
        SESSION_START) echo 0x80000000000000 ;;
        SESSION_START_ONEX_CLI_PIN_CHECK) echo 0x100000000000000 ;;
        HANDOFF_NUDGE) echo 0x200000000000000 ;;
        TASK_BOUNDARY_TESTS) echo 0x400000000000000 ;;
        *) return 1 ;;
    esac
}

# hook_bits_parse_mask RAW
#   Parse a mask string (0x hex, 0b binary, or decimal) into a decimal integer.
#   Returns the parsed value on stdout. On failure, prints HOOK_BITS_DEFAULT_MASK.
hook_bits_parse_mask() {
    local raw="${1:-}"
    if [[ -z "$raw" ]]; then
        echo "$(( HOOK_BITS_DEFAULT_MASK ))"
        return 0
    fi
    case "$raw" in
        0x*|0X*)
            echo "$((raw))"
            ;;
        0b*)
            echo "$(( 2#${raw#0b} ))"
            ;;
        0B*)
            echo "$(( 2#${raw#0B} ))"
            ;;
        *)
            if [[ "$raw" =~ ^[0-9]+$ ]]; then
                echo "$raw"
            else
                echo "$(( HOOK_BITS_DEFAULT_MASK ))"
            fi
            ;;
    esac
}

# hook_bits_is_enabled MASK BIT
#   Exit 0 if BIT is set in MASK, exit 1 otherwise.
#   MASK and BIT may be in any format accepted by $(( ... )).
hook_bits_is_enabled() {
    local mask="$1"
    local bit="$2"
    (( mask & bit ))
}
