name: reviewdog
on:
  pull_request:
    types: [opened, synchronize, reopened]
  merge_group:

jobs:
  reviewdog:
    uses: ./.github/workflows/reviewdog-review.yml
    with:
      python-version: "3.12"
      src-dir: "src/"
      ruff-enabled: true
      mypy-enabled: true
      security-enabled: true
      fail-level: "error"
    secrets:
      REVIEWDOG_PAT: ${{ secrets.REVIEWDOG_PAT }}
